users_index:
    path:     /list
    defaults: { _controller: "CABlogBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "CABlogBundle:Users:show" }
    methods:  GET

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "CABlogBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "CABlogBundle:Users:delete" }
    methods:  DELETE

users_profile:
    path:    /{id}
    requirements:
      id: \d+
    defaults: { _controller: "CABlogBundle:Users:profile", id: 1}

users_profile_username:
     path:    /{username}
     requirements:
       username: \S+
     defaults: { _controller: "CABlogBundle:Users:profile" }
